apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data: 
# BASE64 String: superman@google.com
#  echo -n postgres | base64
  PG_USER_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ==
  DB_PASSWORD: a2luZ3NsYXllcg==
